import React, { useEffect, useState } from "react";
import { getPetsResource } from "../services/message.service";
import { Navbar } from "../components/Navbar"

export const Home = () => {

  return (
      <div>
        <Navbar />
        <h1>TESTING</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet consectetur adipiscing elit ut. Eget nulla facilisi etiam dignissim diam quis. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Donec et odio pellentesque diam. Pellentesque id nibh tortor id aliquet lectus. Augue lacus viverra vitae congue eu consequat. Ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Volutpat sed cras ornare arcu dui vivamus arcu felis. Pretium viverra suspendisse potenti nullam ac. Malesuada bibendum arcu vitae elementum curabitur vitae nunc. Nisl vel pretium lectus quam id leo in. Suspendisse ultrices gravida dictum fusce ut. Vel pretium lectus quam id leo in. In metus vulputate eu scelerisque. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Scelerisque purus semper eget duis at tellus.

Vehicula ipsum a arcu cursus vitae congue. Faucibus nisl tincidunt eget nullam. In ornare quam viverra orci sagittis eu. Nunc consequat interdum varius sit amet. Lorem mollis aliquam ut porttitor leo a diam. Nisi scelerisque eu ultrices vitae auctor eu augue ut. Nunc mi ipsum faucibus vitae aliquet nec. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Hac habitasse platea dictumst vestibulum. Sed libero enim sed faucibus. Quis ipsum suspendisse ultrices gravida dictum. Amet massa vitae tortor condimentum lacinia. Id interdum velit laoreet id donec. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus. At erat pellentesque adipiscing commodo elit at imperdiet dui. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant. At lectus urna duis convallis convallis tellus. Morbi tincidunt ornare massa eget. Bibendum enim facilisis gravida neque convallis.

Quisque non tellus orci ac auctor augue. Augue interdum velit euismod in pellentesque massa placerat duis ultricies. Diam phasellus vestibulum lorem sed risus ultricies. Sed cras ornare arcu dui vivamus arcu. Adipiscing elit pellentesque habitant morbi tristique senectus et. Morbi tincidunt augue interdum velit euismod in pellentesque massa. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Augue ut lectus arcu bibendum. Sit amet consectetur adipiscing elit pellentesque. Quis auctor elit sed vulputate mi. Scelerisque purus semper eget duis at tellus at urna. Euismod elementum nisi quis eleifend quam adipiscing vitae proin sagittis.

Semper viverra nam libero justo laoreet sit amet cursus sit. Nunc mi ipsum faucibus vitae aliquet. Massa enim nec dui nunc mattis. Nibh tortor id aliquet lectus proin nibh nisl condimentum. Neque gravida in fermentum et sollicitudin ac orci phasellus. Ut placerat orci nulla pellentesque dignissim enim sit amet venenatis. Ut diam quam nulla porttitor massa id neque aliquam. Viverra justo nec ultrices dui sapien eget mi. Aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Porta lorem mollis aliquam ut. Purus ut faucibus pulvinar elementum. Sit amet risus nullam eget. At lectus urna duis convallis convallis tellus id interdum.

Sed risus pretium quam vulputate dignissim suspendisse in. Vitae semper quis lectus nulla at volutpat diam ut venenatis. Integer quis auctor elit sed. Ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Ultrices sagittis orci a scelerisque. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim tortor. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Aliquet nec ullamcorper sit amet risus nullam eget. Enim ut sem viverra aliquet. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Amet mattis vulputate enim nulla aliquet porttitor. Sed viverra tellus in hac habitasse platea dictumst. Scelerisque felis imperdiet proin fermentum leo vel orci. Senectus et netus et malesuada fames ac turpis egestas sed. Urna condimentum mattis pellentesque id nibh tortor id aliquet lectus. Pellentesque habitant morbi tristique senectus. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Orci dapibus ultrices in iaculis.</p>
      </div>
  );
};
